[package]
name = "Oxid Boy"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
argparse = "0.2"
blip_buf = "0.1"
bytemuck = "1.20.0"
cpal = "0.15.3"

[dependencies.sdl2]
git = "https://github.com/rust-sdl2/rust-sdl2"
